#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : openshot-qt
Version  : 3.0.0
Release  : 19
URL      : https://github.com/OpenShot/openshot-qt/archive/v3.0.0/openshot-qt-3.0.0.tar.gz
Source0  : https://github.com/OpenShot/openshot-qt/archive/v3.0.0/openshot-qt-3.0.0.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : GPL-2.0 GPL-3.0
Requires: openshot-qt-bin = %{version}-%{release}
Requires: openshot-qt-data = %{version}-%{release}
Requires: openshot-qt-license = %{version}-%{release}
Requires: openshot-qt-python = %{version}-%{release}
Requires: openshot-qt-python3 = %{version}-%{release}
BuildRequires : PyQt5
BuildRequires : buildreq-distutils3
BuildRequires : pyside2-setup
BuildRequires : qscintilla
BuildRequires : sip

%description
To compile a Qt resource file with new translations, follow these steps:
1) Edit the resource file and add the translations to it, using QtCreator
2) Compile this into a Python file, either:
$ make
or, if make is unavailable:
$ pyrcc5 openshot_lang.qrc -o openshot_lang.py

%package bin
Summary: bin components for the openshot-qt package.
Group: Binaries
Requires: openshot-qt-data = %{version}-%{release}
Requires: openshot-qt-license = %{version}-%{release}

%description bin
bin components for the openshot-qt package.


%package data
Summary: data components for the openshot-qt package.
Group: Data

%description data
data components for the openshot-qt package.


%package license
Summary: license components for the openshot-qt package.
Group: Default

%description license
license components for the openshot-qt package.


%package python
Summary: python components for the openshot-qt package.
Group: Default
Requires: openshot-qt-python3 = %{version}-%{release}

%description python
python components for the openshot-qt package.


%package python3
Summary: python3 components for the openshot-qt package.
Group: Default
Requires: python3-core

%description python3
python3 components for the openshot-qt package.


%prep
%setup -q -n openshot-qt-3.0.0
cd %{_builddir}/openshot-qt-3.0.0
pushd ..
cp -a openshot-qt-3.0.0 buildavx2
cp -a openshot-qt-3.0.0 buildavx512
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1672189863
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=auto "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=auto "
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

pushd ../buildavx2/
export CFLAGS="$CFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 -msse2avx "
export CXXFLAGS="$CXXFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 -msse2avx"
export FFLAGS="$FFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export FCFLAGS="$FCFLAGS -m64 -march=x86-64-v3 "
export LDFLAGS="$LDFLAGS -m64 -march=x86-64-v3 "
python3 setup.py build

popd
%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/openshot-qt
cp %{_builddir}/openshot-qt-%{version}/COPYING %{buildroot}/usr/share/package-licenses/openshot-qt/8c71b21b5b902398e19dd8e1f62a2a4075d78d20
cp %{_builddir}/openshot-qt-%{version}/images/Humanity/COPYING %{buildroot}/usr/share/package-licenses/openshot-qt/dfac199a7539a404407098a2541b9482279f690d
cp %{_builddir}/openshot-qt-%{version}/src/resources/license.txt %{buildroot}/usr/share/package-licenses/openshot-qt/c1d5663b31d3742b9487146938059a539e4b4b29
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----
pushd ../buildavx2/
export CFLAGS="$CFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 -msse2avx "
export CXXFLAGS="$CXXFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export FFLAGS="$FFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export FCFLAGS="$FCFLAGS -m64 -march=x86-64-v3 "
export LDFLAGS="$LDFLAGS -m64 -march=x86-64-v3 "
python3 -tt setup.py build install --root=%{buildroot}-v3
popd
/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)
/usr/lib/mime/packages/openshot-qt

%files bin
%defattr(-,root,root,-)
/usr/bin/openshot-qt

%files data
%defattr(-,root,root,-)
/usr/share/applications/org.openshot.OpenShot.desktop
/usr/share/icons/hicolor/128x128/apps/openshot-qt.png
/usr/share/icons/hicolor/256x256/apps/openshot-qt.png
/usr/share/icons/hicolor/512x512/apps/openshot-qt.png
/usr/share/icons/hicolor/64x64/apps/openshot-qt.png
/usr/share/icons/hicolor/scalable/apps/openshot-qt.svg
/usr/share/icons/hicolor/scalable/mimetypes/openshot-qt-doc.svg
/usr/share/metainfo/org.openshot.OpenShot.appdata.xml
/usr/share/mime-packages/org.openshot.OpenShot.xml
/usr/share/pixmaps/openshot-qt.svg

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/openshot-qt/8c71b21b5b902398e19dd8e1f62a2a4075d78d20
/usr/share/package-licenses/openshot-qt/c1d5663b31d3742b9487146938059a539e4b4b29
/usr/share/package-licenses/openshot-qt/dfac199a7539a404407098a2541b9482279f690d

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
